### ISSUE TITLE
urllib2 to urllib

### ISSUE THREAD

**Issue by Clon3d** [Ekultek/Pybelt#10]
# Issue/idea please be specific:
 

# Do you have an idea of how to fix this?

# How can this be reproduced?

# What are the running details of your environment? 
 - Installation method?
 
 
 - Operating system and architecture?
 
 
 - Program version:
 

Change urllib2 to urllib as they were combined in python 3 and causes problems for users when trying to import modules.
 
 - Full traceback exception:
 

# A random fact about yourself

**Comment by Ekultek** [comment]
Where is any of the relevant information? What exactly do you want from me? I no understand!!! 😐

**Comment by Ekultek** [comment]
In other words fix the template and follow it.

**Comment by Ekultek** [comment]
Run it with python 2.7.x I'm not trying to make this compatible with all versions and I'm not going to anytime soon.

**Comment by Ekultek** [comment]
But however this gives me an idea. So I'm gonna keep it open, please try to follow the template next time
