### ISSUE TITLE
i am seeing this type of issue while i try to run pybelt.py

### ISSUE THREAD

**Issue by Najam-ul-islam** [Ekultek/Pybelt#6]
[11:27:50 INFO] Checking program integrity..
Traceback (most recent call last):
  File "pybelt.py", line 85, in <module>
    integrity_check()
  File "/home/najam/Pybelt/lib/core/settings.py", line 294, in integrity_check
    if open("{}\\docs\\checksum.md5".format(PATH)).read() == urllib2.urlopen(url).read():
IOError: [Errno 2] No such file or directory: '/home/najam/Pybelt\\docs\\checksum.md5'

**Comment by Ekultek** [comment]
What OS are you using?

**Comment by psychomad** [comment]
Same for me,
im using Debian 8

**Comment by Ekultek** [comment]
I know what the problem is, give me some time. It was built on Windows so the paths are wrong

**Comment by psychomad** [comment]
No prob, just gave my voice too :D

**Comment by Ekultek** [comment]
Fixed via c677e19

**Comment by psychomad** [comment]
Thanks a lot!

**Comment by Najam-ul-islam** [comment]
i am using kali linux which is Debian based

**Comment by Najam-ul-islam** [comment]
still it does not works for me

**Comment by Ekultek** [comment]
Did you clone the newest version?

**Comment by Ekultek** [comment]
Fixed via 3b81775

**Comment by Najam-ul-islam** [comment]
yah bro i cloned newest

**Comment by Ekultek** [comment]
![working_pybelt](https://cloud.githubusercontent.com/assets/14183473/26246857/d1983d00-3c60-11e7-8b9b-36a50a654f98.PNG)


Parrot is Debian based like Kali, download newest version or clone it, and try again. I'll keep this open until you reply back

**Comment by Ekultek** [comment]
24 hours no complaints, guessing it worked. Closing this down
