### ISSUE TITLE
python google module

### ISSUE THREAD

**Issue by noptrix** [Ekultek/Pybelt#8]
Hi,

I am getting the following error when running pybelt although all dependencies are installed. It's related to the google module and i can't find 'search' from 'google' in python2.7. OS is Arch Linux and google module is in verion 1.9.3 from pypi:

```
Traceback (most recent call last):
  File "pybelt.py", line 8, in <module>
    from lib.pointers import run_proxy_finder
  File "/usr/share/pybelt/lib/pointers.py", line 9, in <module>
    from lib.core.dork_check import DorkScanner
  File "/usr/share/pybelt/lib/core/__init__.py", line 1, in <module>
    from dork_check import DorkScanner
  File "/usr/share/pybelt/lib/core/dork_check/__init__.py", line 1, in <module>
    from dorks import DorkScanner
  File "/usr/share/pybelt/lib/core/dork_check/dorks.py", line 5, in <module>
    from google import search
ImportError: cannot import name search
```

**Comment by Ekultek** [comment]
Arch or Black Arch?

**Comment by Ekultek** [comment]
A couple things could cause this, one there's a file on your system that has the same name `search` and it's trying to import from there, two you didn't install the dependencies from `pip -r requirements.txt`, three it's a bug. 

What I need:
 - Are you using arch or black arch?
 - Did you run `pip install -r requirments.txt` before running the application?
 - What version of `pybelt` do you have? `python pybelt.py --version`
 - How did you get it? `git clone`, `tarball`, etc.. ?
 - Also what is the exact command you are running?

**Comment by noptrix** [comment]
@Ekultek thanks for the quick response. Archlinux (blackarch itself is more just a repository on top of arch linux). No, we don't use 'pip -r'. What we do is to add the dependencies manually. If I run ipython2 and try to include: 'from google import search' the search method is not loaded with the same error like above.

coming to your questions:

- archlinux
- no
- current version (git clone from https://github.com/Ekultek/Pybelt.git)
- git clone
- pybelt

**Comment by Ekultek** [comment]
Well while you wait for me to do my research go play with this: https://github.com/Ekultek/Dagon

You'll like it I promise!

**Comment by noptrix** [comment]
thanks, will be added to BA

**Comment by Ekultek** [comment]
Is this another issue like the whitewidow one?

**Comment by Ekultek** [comment]
Alright, so I have a question for you. _IF_ you do use it with `pip install -r requirements.txt` does it work?

**Comment by noptrix** [comment]
no no, it's not the same like whitewidow :)

**Comment by noptrix** [comment]
i will try the 'pip -r' one later and let you know.

**Comment by Ekultek** [comment]
Cool, let me know

**Comment by Ekultek** [comment]
@noptrix Any news on this?

**Comment by Ekultek** [comment]
Haven't heard anything about this in a week, closing this down.
